### PR TITLE
Add coverage reports

### PR DESCRIPTION
**Pull request by jcollado**
This PR adds coverage reports using istanbul.

### CODE REVIEW

**Comment by jcollado** [comment]
@juliangruber If you're interested, I can create another PR to upload coverage reports to coveralls.io from travis and add a coverage badge to the readme file.

**Comment by juliangruber** [comment]
thanks!

i added another commit that makes istanbul actually run all the tests: https://github.com/juliangruber/validimir/commit/cdd48f30ffd4c27d7ccfe9178437246b96763dcd

coverage is now at 98.59%

**Comment by jcollado** [comment]
Great. I'm also thinking about adding more test cases, but the coverage is quite good already.

**Comment by juliangruber** [comment]
coverage is 100% now :)

**Comment by juliangruber** [comment]
> @juliangruber If you're interested, I can create another PR to upload coverage reports to coveralls.io from travis and add a coverage badge to the readme file.

that would be great!

**Pull request merged**
