### PR TITLE
provide extensibility though exposing the checks array

### PR DESCRIPTION
**Pull request by 0x00A**
With this PR, custom functions could be added, for instance...

```js
function Foo(o) {

  var validimir = Validimir()

  validimir.date = function(date) {
    validimir.checks.push(function(v) {
      if (!(v instanceof Date) || isNaN(v.valueOf()) ) {
        return {
          value: v,
          operator: 'equal',
          expected: date
        }
      }
    })
    return validimir
  }

  Object
    .keys(validimir)
    .forEach(function(name) {
      this[name] = validimir[name]
    }.bind(this))
  // ...
}
```

### CODE REVIEW

**Comment by juliangruber** [comment]
for convenience i added `.date()` to 1.1.0.

if we expose `.checks` we also need to fully document its api. we can def. do that but for now I suggest let's keep adding validations to validimir until we find one that doesn't fit in.

**Comment by jcollado** [comment]
I'm working on updating to `validimir` a piece of code that uses [`validator.isURL`](https://github.com/chriso/validator.js/blob/master/validator.js#L232) under the hood. Without a way to add custom validation functions that cannot be done for now.

@juliangruber I can add the documentation that you think is needed before exposing `checks` if you wish. Also, we can talk about not exposing `checks`, but just a function to append a custom validation function that can be chained as the other functions if you think that would be a safer approach.

**Comment by juliangruber** [comment]
I'm up for adding that to validator master

**Comment by jcollado** [comment]
Now that #19 has been merged, this shouldn't be needed anymore.

**Pull request closed without merging**
